// 这个文件是 MCF 的一部分。
// 有关具体授权说明，请参阅 MCFLicense.txt。
// Copyleft 2013 - 2015, LH_Mouse. All wrongs reserved.

#ifndef MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
#	error MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_ is not defined.
#endif

#ifndef MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_
#	error MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ is not defined.
#endif

MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
bool operator==(const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &lhs,
	const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &rhs) noexcept
{
	return lhs.Get() == rhs.Get();
}
MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
bool operator==(const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &lhs, ObjectT *rhs) noexcept {
	return lhs.Get() == rhs;
}
MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
bool operator==(ObjectT *lhs, const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &rhs) noexcept {
	return lhs == rhs.Get();
}

MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
bool operator!=(const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &lhs,
	const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &rhs) noexcept
{
	return lhs.Get() != rhs.Get();
}
MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
bool operator!=(const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &lhs, ObjectT *rhs) noexcept {
	return lhs.Get() != rhs;
}
MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
bool operator!=(ObjectT *lhs, const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &rhs) noexcept {
	return lhs != rhs.Get();
}

MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
bool operator<(const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &lhs,
	const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &rhs) noexcept
{
	return lhs.Get() < rhs.Get();
}
MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
bool operator<(const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &lhs, ObjectT *rhs) noexcept {
	return lhs.Get() < rhs;
}
MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
bool operator<(ObjectT *lhs, const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &rhs) noexcept {
	return lhs < rhs.Get();
}

MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
bool operator>(const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &lhs,
	const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &rhs) noexcept
{
	return lhs.Get() > rhs.Get();
}
MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
bool operator>(const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &lhs, ObjectT *rhs) noexcept {
	return lhs.Get() > rhs;
}
MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
bool operator>(ObjectT *lhs, const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &rhs) noexcept {
	return lhs > rhs.Get();
}

MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
bool operator<=(const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &lhs,
	const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &rhs) noexcept
{
	return lhs.Get() <= rhs.Get();
}
MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
bool operator<=(const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &lhs, ObjectT *rhs) noexcept {
	return lhs.Get() <= rhs;
}
MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
bool operator<=(ObjectT *lhs, const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &rhs) noexcept {
	return lhs <= rhs.Get();
}

MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
bool operator>=(const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &lhs,
	const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &rhs) noexcept
{
	return lhs.Get() >= rhs.Get();
}
MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
bool operator>=(const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &lhs, ObjectT *rhs) noexcept {
	return lhs.Get() >= rhs;
}
MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
bool operator>=(ObjectT *lhs, const MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &rhs) noexcept {
	return lhs >= rhs.Get();
}

MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
void swap(MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &lhs,
	MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_ &rhs) noexcept
{
	lhs.Swap(rhs);
}

#undef MCF_SMART_POINTERS_DECLARE_TEMPLATE_PARAMETERS_
#undef MCF_SMART_POINTERS_INVOKE_TEMPLATE_PARAMETERS_
