#!/bin/bash

set -e

export CFLAGS="-O3 -ffunction-sections -fdata-sections"
export CXXFLAGS="-O3 -ffunction-sections -fdata-sections"
export LDFLAGS="-O3 -Wl,-s,--gc-sections"

mkdir -p .tmp/MCFBuild
cd .tmp/MCFBuild
../../configure
make -j4
